# Generated by Django 3.2.15 on 2022-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
