# Generated by Django 3.2.15 on 2022-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0003_auto_20221017_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='link_diario_oficial',
            field=models.URLField(default='https://culturanf.novafriburgo.rj.gov.br/editais/cultura-planeja'),
            preserve_default=False,
        ),
    ]
