# Generated by Django 3.2.15 on 2022-10-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0005_edital_link_resultado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['-id', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='downloads',
            options={'ordering': ['-id'], 'verbose_name': 'Download', 'verbose_name_plural': 'Downloads'},
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['-id'], 'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AddField(
            model_name='edital',
            name='dt_divulgacao',
            field=models.DateField(default='2022-11-20', verbose_name='Data de divulgação do local e horário da prova'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='link_digulvacao',
            field=models.URLField(blank=True, null=True, verbose_name='Link com local de prova e horário'),
        ),
        migrations.AddField(
            model_name='edital',
            name='vagas',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='vagas_reservadas',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='deficiente',
            field=models.BooleanField(default=False, verbose_name='Adequado p/ deficiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='qnt_alocação',
            field=models.IntegerField(default=14, verbose_name='Quantas alocações é permitida?'),
            preserve_default=False,
        ),
    ]
