# Generated by Django 3.2.15 on 2022-10-19 20:16

from django.db import migrations, models
import selecao.functions


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0006_auto_20221019_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='autodeclaracao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='O candidato autodeclarado preto, pardo ou indígena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='ensino_fundamental_publico',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='O candidato cursou o ensino fundamental integralmente em escola pública?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='ensino_medio_publico',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='O candidato cursou o ensino médio integralmente em escola pública?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='file_necessidade',
            field=models.FileField(blank=True, null=True, upload_to='file_necessidade', verbose_name='Anexo em PDF de justificativa da necessidade por médico especializado'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='file_tempo_excedente',
            field=models.FileField(blank=True, null=True, upload_to='file_tempo_excedente', verbose_name='Anexo em PDF de justificativa para tempo excedente de médico especializado'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='file_termo_para_vagas_reservadas',
            field=models.FileField(blank=True, null=True, upload_to='file_adesao_sis_vagas_reservadas', verbose_name='Anexo em PDF do Termo de Adesão ao Sistema de Vagas Reservadas'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='renda_bruta',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='O candidato possui renda bruta mensal igual ou inferior a 1,5 salários mínimos per capita?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='tempo_excedente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Informe se necessita de tempo excedente para a realização da prova'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[selecao.functions.validate_CPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='deficiencia',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Possui deficiência?'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.CharField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='necessidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Informe se necessita de alguma condição especial para a realização da prova'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='qual_deficiencia',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Indique qual a deficiência'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone'),
        ),
    ]
