# Generated by Django 3.1.4 on 2022-10-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0007_auto_20221019_1716'),
        ('selecao', '0006_auto_20221018_1845'),
    ]

    operations = [
    ]
