# Generated by Django 3.2.13 on 2022-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0008_auto_20221021_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='deficiencia',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Possui deficiência?'),
        ),
    ]
