# Generated by Django 3.1.4 on 2022-10-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0010_auto_20221021_1535'),
        ('selecao', '0008_merge_20221021_0959'),
        ('selecao', '0008_auto_20221023_1429'),
    ]

    operations = [
    ]
