# Generated by Django 3.2.13 on 2022-10-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0008_auto_20221023_1429'),
        ('selecao', '0010_auto_20221021_1535'),
    ]

    operations = [
    ]
