# Generated by Django 3.2.15 on 2022-10-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0008_alter_candidato_autodeclaracao'),
        ('selecao', '0008_auto_20221023_1429'),
        ('selecao', '0010_auto_20221021_1535'),
    ]

    operations = [
    ]
