# Generated by Django 3.2.15 on 2022-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0011_merge_20221025_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='autodeclaracao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='O candidato é autodeclarado preto, pardo ou indígena'),
        ),
    ]
