# Generated by Django 3.2.13 on 2022-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0012_alter_candidato_autodeclaracao'),
        ('selecao', '0012_auto_20221023_2023'),
    ]

    operations = [
    ]
