# Generated by Django 3.2.15 on 2022-10-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0012_alter_candidato_autodeclaracao'),
        ('selecao', '0012_auto_20221023_2023'),
    ]

    operations = [
    ]
