# Generated by Django 3.2.13 on 2022-11-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0013_merge_20221108_1432'),
    ]

    operations = []
