# Generated by Django 4.2.23 on 2025-08-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0014_auto_20221108_1432'),
        ('selecao', '0014_auto_20221206_1116'),
    ]

    operations = [
    ]
