# Generated by Django 3.2.13 on 2022-11-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0014_auto_20221103_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selecao.candidato')),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'ordering': ['nota'],
            },
        ),
    ]
