# Generated by Django 4.2.23 on 2025-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0015_merge_0014_auto_20221108_1432_0014_auto_20221206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='numero_inscricao',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='file_necessidade',
            field=models.FileField(blank=True, null=True, upload_to='file_necessidade', verbose_name='Anexar em PDF a justificativa da necessidade por médico especializado.'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='file_tempo_excedente',
            field=models.FileField(blank=True, null=True, upload_to='file_tempo_excedente', verbose_name='Anexar em PDF a justificativa para tempo excedente de médico especializado.'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='file_termo_para_vagas_reservadas',
            field=models.FileField(blank=True, null=True, upload_to='file_adesao_sis_vagas_reservadas', verbose_name='Anexar em PDF o Termo de Adesão ao Sistema de Vagas Reservadas, devidamente preenchido e assinado (Anexo 1 do Edital).'),
        ),
    ]
