# Generated by Django 4.2.23 on 2025-09-05 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0016_candidato_numero_inscricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='numero_inscricao',
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
